### ISSUE TITLE
Question about WordPress author

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-import#123]
Is there any reason the WordPress importer saves author information as:

``` yaml
author: John Doe
author_login: jdoe
author_email: jdoe@example.com
author_url: http://example.com/jdoe
```

rather than

``` yaml
author:
  login: jdoe
  email: jdoe@example.com
  display_name: John Doe
  first_name: John
  last_name: Doe
```

:question:

Just curious.
