### ISSUE TITLE
Filename too long (ENAMETOOLONG) crash instead of renaming

### ISSUE THREAD

**Issue by pathetiq** [jekyll/jekyll-import#240]
Hi,

When importing WordPress (hosted on my own server) data I got an error of a filename too long as some of our post title we use for long description.

```
$ sh jekyll-import.sh    
/var/lib/gems/1.9.1/gems/jekyll-import-0.10.0/lib/jekyll-import/importers/wordpress.rb:329:in 'initialize': File name too long - _posts/2013-07-11-pour-une-4e-annee-consecutive-nous-sommes-heureux-daccueillir-les-technologies-wolf-en-tant-que-partenaire-cafe-merci-pour-votre-support.html (Errno::ENAMETOOLONG)
        from /var/lib/gems/1.9.1/gems/jekyll-import-0.10.0/lib/jekyll-import/importers/wordpress.rb:329:in 'open'
        from /var/lib/gems/1.9.1/gems/jekyll-import-0.10.0/lib/jekyll-import/importers/wordpress.rb:329:in 'process_post'
        from /var/lib/gems/1.9.1/gems/jekyll-import-0.10.0/lib/jekyll-import/importers/wordpress.rb:166:in 'block in process'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/dataset/actions.rb:141:in 'block in each'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/adapters/mysql2.rb:162:in 'block (2 levels) in fetch_rows'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/adapters/mysql2.rb:162:in 'each'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/adapters/mysql2.rb:162:in 'block in fetch_rows'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/adapters/mysql2.rb:93:in '_execute'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/adapters/shared/mysql_prepared_statements.rb:36:in 'block in execute'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/database/connecting.rb:251:in 'block in synchronize'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/connection_pool/threaded.rb:105:in 'hold'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/database/connecting.rb:251:in 'synchronize'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/adapters/shared/mysql_prepared_statements.rb:36:in 'execute'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/dataset/actions.rb:952:in 'execute'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/adapters/mysql2.rb:197:in 'execute'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/adapters/mysql2.rb:156:in 'fetch_rows'
        from /var/lib/gems/1.9.1/gems/sequel-4.31.0/lib/sequel/dataset/actions.rb:141:in 'each'
        from /var/lib/gems/1.9.1/gems/jekyll-import-0.10.0/lib/jekyll-import/importers/wordpress.rb:165:in 'process'
        from /var/lib/gems/1.9.1/gems/jekyll-import-0.10.0/lib/jekyll-import/importer.rb:23:in 'run'
        from -e:2:in '<main>'
```

> sh jekyll-import.sh : is simply the script here: http://import.jekyllrb.com/docs/wordpress/

Is there an easy way to shorten the file name and continue the import instead of just crashing?

Thanks

**Comment by parkr** [comment]
Hey @pathetiq!

> Is there an easy way to shorten the file name and continue the import instead of just crashing?

Yes, this should be fairly straightforward. How long can a name be? You'll want to trim it as appropriate (perhaps trimming whole words instead of just characters? or using the wordpress slug if there was one?). [Here is the code that creates the post name](https://github.com/jekyll/jekyll-import/blob/e88c3f59358bc7b8205823b8e1c688ba2fe51d41/lib/jekyll-import/importers/wordpress.rb#L322-L326).

**Comment by pathetiq** [comment]
Thanks for the fast reply.

It appears that on ubuntu the max length is 127.

I fixed it with a simple:
```ruby
if filename.length > 127
     filename = filename.byteslice(127)
end
```

I did found some anomalies where some file won't have a filename and would be name a single letter of the alphabet and even a dot (.) and it will crash saying the filename is a directory.

This has been bypass with the following but I'm pretty sure something weird is happening:
```ruby
if filename == '.'
     filename = filename+"-ERROR"
end
```

I can send a few files if needed.

Thanks again

**Comment by parkr** [comment]
@pathetiq It sounds strange that there would be some anomalies where the filename would be a single letter or even just a dot...

What happens if you set the sluggify method to:

```ruby
      def self.sluggify( title )
        title = title.to_ascii.downcase.gsub(/[^0-9A-Za-z]+/, " ").strip.split(/\s+/).take(8).join("-")
      end
```

This will limit the slug to 8 words. Your example had well over 10, so this should help limit every title-turned-slug.

**Comment by pathetiq** [comment]
Changing the sluggify function to 8 doesn't fix the length problem (really think it is 127 max) and neither the weird 1 character long filename.

Though, I think I might know the problem for the 1 char filename. It seems that some WordPress post have badly form HTML inside the title and it will cause this behaviour. 

Here is an example of a 1 char filename file (filename is: m):
```yaml
---
layout: post
status: publish
published: true
title: ! '<a href="http:&#47;&#47;www.website.com&#47;speakers#cg">Event 2015 Conf&eacute;rence:
  Christine Gagnon de Website.org offrira une conf&eacute;rence d''introduction
  et une formation pratique sur le comportement humaine nomm&eacute;e "Analyse du
  comportement humain : Identifier le &laquo;Red Flag&raquo; et s&rsquo;en servir"<&#47;a>'
author:
  display_name: Author name
  login: username
  email: my@email.com
  url: ''
author_login: username
author_email: my@email.com
wordpress_id: 6285
wordpress_url: http://www.website.com/?p=6285
date: !binary |-
  MjAxNS0xMC0wOCAyMDo1Njo0MCAtMDQwMA==
date_gmt: !binary |-
  MjAxNS0xMC0wOSAwMDo1Njo0MCAtMDQwMA==
categories:
- News
- Francais
- Network
tags:
- conference
- event 2015
comments: []
---
```

Here is a regular file (filename is: 2014-11-11-les-resultats-du-event-ctf-2014-sont-disponibles.html):
```yaml
---
layout: post
status: publish
published: true
title: <!--:fr--> <a href="http:&#47;&#47;www.website.com&#47;games-2014">Les
  r&eacute;sultats du EVENT 2014 sont disponibles<&#47;a> <!--:--> <!--:en-->
  <a href="http:&#47;&#47;www.website.com&#47;en&#47;games-2014">Event
  2014 Results are online<&#47;a> <!--:-->
author:
  display_name: Author name
  login: username
  email: my@email.com
  url: ''
author_login: username
author_email: my@email.com
wordpress_id: 5765
wordpress_url: http://www.website.com/?p=5765
date: !binary |-
  MjAxNC0xMS0xMSAwMDozMzowMSAtMDUwMA==
date_gmt: !binary |-
  MjAxNC0xMS0xMSAwNTozMzowMSAtMDUwMA==
categories:
- News
- Francais
- Anglais
- Network
tags:
- ctf
- '2014'
- results
- gagnant
comments: []
---
```

On a side note this is run on:
- Ubuntu 14.04.4 LTS
- 64 bits
